version = 0.1
[default.deploy.parameters]
stack_name = "AI4NG-T1-Training-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-elqih9cswhbb"
s3_prefix = "AI4NG-T1-Training-dev"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []