AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Roles for EEG Processing Pipeline
Resources:
  #IAM Roles
  # --- ECS Task Execution Role (for ECS agent) ---
  EEGTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EEGTaskExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: ECRAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: "*"

  # --- ECS Task Role (for application container) ---
  EEGTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EEGTaskRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DataAccessPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # S3 access for input/output data
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${EEGUploadBucketName}
                  - !Sub arn:aws:s3:::${EEGUploadBucketName}/*
                  
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - !Sub arn:aws:s3:::${EEGResultsBucket}
                  - !Sub arn:aws:s3:::${EEGResultsBucket}/*
                  
              # DynamoDB access for status updates
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                Resource: !GetAtt ProcessingStatusTable.Arn

Outputs:
  EEGStepFunctionRoleArn:
    Value: !GetAtt EEGStepFunctionRole.Arn
    Export:
      Name: EEGStepFunctionRoleArn
  EEGTaskExecutionRoleArn:
    Value: !GetAtt EEGTaskExecutionRole.Arn
    Export:
      Name: EEGTaskExecutionRoleArn
  EEGTaskRoleArn:
    Value: !GetAtt EEGTaskRole.Arn
    Export:
      Name: EEGTaskRoleArn