AWSTemplateFormatVersion: '2010-09-09'
Description: EEG Processing Pipeline with Mobile Status Tracking
Transform: AWS::Serverless-2016-10-31

Parameters:
  SharedApiId:
    Type: String
    Description: ID of the shared API Gateway
  EEGUploadBucketName:
    Type: String
    Description: Name of the existing EEG upload bucket
  PrivateSG:
    Type: String
    Description: Security group ID for private resources
  PrivateSubnetId1:
    Type: String
    Description: First private subnet ID
  PrivateSubnetId2:
    Type: String
    Description: Second private subnet ID

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "API Configuration"
        Parameters:
          - SharedApiId
      - Label:
          default: "Network Configuration"
        Parameters:
          - PrivateSG
          - PrivateSubnetId1
          - PrivateSubnetId2
      - Label:
          default: "S3 Configuration"
        Parameters:
          - EEGUploadBucketName

Resources:
  # --- S3 Buckets ---
  EEGResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ai4ng-eeg-results-${AWS::AccountId}-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  EEGResultsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref EEGResultsBucket
      PolicyDocument:
        Statement:
          - Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource: 
              - !GetAtt EEGResultsBucket.Arn
              - !Sub "${EEGResultsBucket.Arn}/*"
            Condition:
              Bool:
                "aws:SecureTransport": true

  # --- DynamoDB Tables ---
  ProcessingStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: EEGProcessingStatus
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: expiry
        Enabled: true

  EEGClassifierTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FBCSPClassifierParameters
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # --- API Gateway Integration ---
  StatusIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SharedApiId
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetStatusLambda.Arn}/invocations
      PayloadFormatVersion: "2.0"
      IntegrationMethod: POST

  StatusRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SharedApiId
      RouteKey: "GET /api/status/{sessionId}"
      AuthorizationType: JWT
      AuthorizerId: !ImportValue SharedApiAuthorizerId
      Target: !Sub integrations/${StatusIntegration}

  # --- Lambda Functions ---
  # HTTP GET Lambda for Status Check
  GetStatusLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/lambdas/statusCheck/
      Handler: app.handler
      Runtime: nodejs22.x
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          STATUS_TABLE: !Ref ProcessingStatusTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProcessingStatusTable
      # Integrated permission for API Gateway
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: SQS
            Destination: !GetAtt StatusQueue.Arn

  GetStatusLambdaPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt GetStatusLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${SharedApiId}/*/GET/api/status/{sessionId}"

  # S3 Event Triggered Lambdas
  # Processes manifest.json files uploaded to the EEGResultsBucket
  # and updates the processing status in DynamoDB
  ManifestProcessorLambda:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref EEGResultsBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: manifest.json
      CodeUri: ../src/lambdas/manifestProcessor/
      Handler: app.handler
      Runtime: nodejs22.x
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          STATUS_TABLE: !Ref ProcessingStatusTable
          SNS_TOPIC_ARN: !Ref ProcessingNotificationTopic
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref ProcessingStatusTable
        - S3ReadPolicy:
            BucketName: !Ref EEGResultsBucket
        - Statement:  
          - Effect: Allow
            Action: sns:Publish
            Resource: !Ref ProcessingNotificationTopic

  ClassifierProcessorLambda:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref EEGResultsBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .json
      CodeUri: ../src/lambdas/classifierProcessor/
      Handler: app.handler
      Runtime: nodejs22.x
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          CLASSIFIER_TABLE: !Ref EEGClassifierTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref EEGClassifierTable
        - S3ReadPolicy:
            BucketName: !Ref EEGResultsBucket

  ResultsMetadataLambda:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref EEGResultsBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .json
      CodeUri: ../src/lambdas/resultsMetadata/
      Handler: app.handler
      Runtime: nodejs22.x
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          STATUS_TABLE: !Ref ProcessingStatusTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref ProcessingStatusTable
        - S3ReadPolicy:
            BucketName: !Ref EEGResultsBucket

  ProcessingNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: EEGProcessingNotifications
      DisplayName: EEG Processing Notifications
      Subscription:
        - Protocol: email
          Endpoint: 'hss70@bath.ac.uk'

  StatusQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: EEG-Status-Queue
      
  # --- IAM Roles ---
  EEGTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${EEGUploadBucketName}"
                  - !Sub "arn:aws:s3:::${EEGUploadBucketName}/*"
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - !GetAtt EEGResultsBucket.Arn
                  - !Sub "${EEGResultsBucket.Arn}/*"
        - PolicyName: DynamoDBStatusUpdate
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                Resource: !GetAtt ProcessingStatusTable.Arn
        - PolicyName: ECRAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: "*"

  # --- Step Function Execution Role ---
  EEGStepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: 
                  - !GetAtt ClassifierProcessorLambda.Arn
                  - !GetAtt ResultsMetadataLambda.Arn
                  - !GetAtt ManifestProcessorLambda.Arn
              - Effect: Allow
                Action:
                  - ecs:RunTask
                  - ecs:StopTask
                  - ecs:DescribeTasks
                Resource: "*"
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt EEGTaskExecutionRole.Arn
              - Effect: Allow
                Action:
                  - events:PutTargets
                  - events:PutRule
                  - events:DescribeRule
                Resource: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctions*

  # --- ECS Resources ---
  EEGFargateCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: EEG-Classifier-Cluster
      ClusterSettings:
        - Name: containerInsights
          Value: enabled

  ClassifierLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/eeg-classifier
      RetentionInDays: 30

  ClassifierECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: eeg-classifier
      ImageTagMutability: MUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPrefixList": ["v"],
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": { "type": "expire" }
              }
            ]
          }

  EEGFargateTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: EEGClassifierTask
      Cpu: '1024'
      Memory: '4096'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt EEGTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: eeg-classifier
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ClassifierECR}:latest
          Essential: true
          Environment:
            - Name: UPLOAD_BUCKET
              Value: !Ref EEGUploadBucketName
            - Name: RESULTS_BUCKET
              Value: !Ref EEGResultsBucket
            - Name: STATUS_TABLE
              Value: !Ref ProcessingStatusTable
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ClassifierLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: eeg-classifier

  # --- Step Functions ---
  ProcessingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: infra/state-machine.asl.json
      Role: !GetAtt EEGStepFunctionRole.Arn
      Tags:
        AI4NG: "true"
        TrainingPipeline: "true"
      Events:
        S3UploadTrigger:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source: ["aws.s3"]
              detail-type: ["Object Created"]
              detail:
                bucket:
                  name: [!Ref EEGUploadBucketName]
                object:
                  key:
                    prefix: "uploads/"
                    suffix: ".zip"

Outputs:
  StatusApiUrl:
    Value: !Sub https://${SharedApiId}.execute-api.${AWS::Region}.amazonaws.com/dev/api/status/
    Description: URL for status checking API
    Export:
      Name: EEGStatusApiUrl
  ResultsBucketName:
    Value: !Ref EEGResultsBucket
    Export:
      Name: EEGResultsBucketName
  ECRRepositoryUri:
    Value: !GetAtt ClassifierECR.RepositoryUri 
    Description: URI for the ECR repository containing the classifier image
    Export:
      Name: EEGClassifierECRUri
  ProcessingStateMachineArn:
    Value: !Ref ProcessingStateMachine
    Description: ARN of the EEG processing state machine
    Export:
      Name: EEGProcessingStateMachineArn