function Hd = filterone
%FILTERONE Returns a discrete-time filter object.

global fs

% MATLAB Code
% Generated by MATLAB(R) 7.12 and the Signal Processing Toolbox 6.15.
%
% Generated on: 08-Feb-2013 16:02:44
%

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

N  = 5;   % Order
Fc = 10;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');


% Other filters

%       Ap    - Passband Ripple (dB)
%       Ast   - Stopband Attenuation (dB)
%       F3dB  - 3dB Frequency
%       Fc    - Cutoff Frequency
%       Fp    - Passband Frequency
%       Fst   - Stopband Frequency
%       N     - Filter Order
%       Nb    - Numerator Order
%       Na    - Denominator Order


% D = fdesign.lowpass('Fp,Fst,Ap,Ast',0.2,0.25,1,60);
% Hd = design(D,'equiripple','StopBandShape','linear','StopBandDecay',20);
% fvtool(Hd);

%   % Example #1 - Design a minimum-order equiripple lowpass filter. 
%   % Specify ripples in linear units.
%   d  = fdesign.lowpass('Fp,Fst,Ap,Ast',0.1,0.12,0.1,1e-4,'linear');
%   Hd = design(d, 'equiripple');
%   fvtool(Hd)
%
%   % Example #2 - Design a minimum-phase FIR lowpass filter with
%   % equiripple passband and a stopband that decays as (1/f)^2. (*)
%   d  = fdesign.lowpass('N,Fp,Fst',6,0.3,10,125);
% %   designopts(d,'equiripple') % List equiripple design options
%   Hd = design(d,'equiripple','StopbandShape','1/f','StopbandDecay',2,...
%        'minphase',true);
%   fvtool(Hd)
%
  % Example #3 - Design a Chebyshev Type I IIR filter with a passband 
  % ripple of 0.5 dB and a 3 dB cutoff frequency at 125 Hz. (*)
%   Fs = 125; % Sampling frequency of input signal
%   d  = fdesign.lowpass('N,F3dB,Ap', N, Fc, .5, Fs);
%   Hd = design(d, 'cheby1');
%   fvtool(Hd)






















% [EOF]
