name: Deploy Infrastructure
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/**'
      - '!infra/EEGProcessingStateMachine.asl.json'
      - '!**/*.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-2
      STACK_NAME: EEG-Training-Pipeline

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Get exported values from CloudFormation
      - name: Get Shared API ID from CloudFormation export
        id: get_exports
        run: |
          echo "Fetching CloudFormation exports..."
          API_ID=$(aws cloudformation list-exports \
            --query "Exports[?Name=='SharedApiId'].Value" \
            --output text)
          BUCKET_NAME=$(aws cloudformation list-exports \
            --query "Exports[?Name=='EEGUploadBucketName'].Value" \
            --output text)
          
          # Verify values exist
          if [ -z "$API_ID" ]; then
            echo "::error::SharedApiId export not found"
            exit 1
          fi
          if [ -z "$BUCKET_NAME" ]; then
            echo "::error::EEGUploadBucketName export not found"
            exit 1
          fi
          
          echo "api_id=$API_ID" >> $GITHUB_OUTPUT
          echo "bucket_name=$BUCKET_NAME" >> $GITHUB_OUTPUT

      - name: Validate CloudFormation templates
        run: |
          aws cloudformation validate-template --template-body file://infra/IAM.yaml
          aws cloudformation validate-template --template-body file://infra/trainingPipelineTemplate.yaml

      - name: Deploy IAM Stack
        run: |
          aws cloudformation deploy \
            --template-file infra/IAM.yaml \
            --stack-name ${STACK_NAME}-IAM \
            --capabilities CAPABILITY_IAM

      - name: Deploy Main Pipeline Stack
        run: |
          aws cloudformation deploy \
            --template-file infra/trainingPipelineTemplate.yaml \
            --stack-name ${STACK_NAME}-Main \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              SharedApiId=${{ steps.get_exports.outputs.api_id }} \
              EEGUploadBucketName=${{ steps.get_exports.outputs.bucket_name }}