name: Deploy Infrastructure

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-2
      STACK_NAME: EEG-Training-Pipeline

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate CloudFormation templates
        run: |
          aws cloudformation validate-template --template-body file://infra/IAM.yaml
          aws cloudformation validate-template --template-body file://infra/trainingPipelineTemplate.yaml

      - name: Deploy IAM Stack
        run: |
          aws cloudformation deploy \
            --template-file infra/IAM.yaml \
            --stack-name ${STACK_NAME}-IAM \
            --capabilities CAPABILITY_IAM

      - name: Deploy Main Pipeline Stack
        run: |
          aws cloudformation deploy \
            --template-file infra/trainingPipelineTemplate.yaml \
            --stack-name ${STACK_NAME}-Main \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              SharedApiId=${{ secrets.API_GATEWAY_ID }} \
              EEGUploadBucketName=${{ secrets.EEG_UPLOAD_BUCKET }}