name: Deploy Infrastructure
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/deploy-infra.yml'
      - 'infra/**'
      - '!infra/EEGProcessingStateMachine.asl.json'
      - '!**/*.md'
      - 'src/PostProcessingLambdas/**'  # Include Lambda source code
      - 'samconfig.toml'  # Include SAM configuration file

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-2
      STACK_NAME: AI4NG-T1-Training-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Install SAM CLI
      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli
          sam --version

      # Get all required exported values
      - name: Get CloudFormation exports
        id: get_exports
        run: |
          echo "Fetching CloudFormation exports..."
          BUCKET_NAME=$(aws cloudformation list-exports \
            --query "Exports[?Name=='EEGUploadBucketName'].Value" \
            --output text)
          
          SHARED_API_ID=$(aws cloudformation list-exports \
            --query "Exports[?Name=='SharedApiId'].Value" \
            --output text)
          if [ -z "$SHARED_API_ID" ]; then
            echo "::error::SharedApiId export not found" 
          
          SG_ID=$(aws cloudformation list-exports \
            --query "Exports[?Name=='NetworkStack-PrivateSG'].Value" \
            --output text)
          
          SUBNETS_STRING=$(aws cloudformation list-exports \
            --query "Exports[?Name=='NetworkStack-PrivateSubnetIds'].Value" \
            --output text)
          
          SUBNET1=$(echo "$SUBNETS_STRING" | cut -d',' -f1)
          SUBNET2=$(echo "$SUBNETS_STRING" | cut -d',' -f2)
          
          # Verify values
          if [ -z "$BUCKET_NAME" ]; then
            echo "::error::EEGUploadBucketName export not found"
            exit 1
          fi
          if [ -z "$SG_ID" ]; then
            echo "::error::NetworkStack-PrivateSG export not found"
            exit 1
          fi
          if [ -z "$SUBNETS_STRING" ]; then
            echo "::error::NetworkStack-PrivateSubnetIds export not found"
            exit 1
          fi
          if [ -z "$SUBNET1" ] || [ -z "$SUBNET2" ]; then
            echo "::error::Could not parse subnets from: $SUBNETS_STRING"
            exit 1
          fi
          
          echo "bucket_name=$BUCKET_NAME" >> $GITHUB_OUTPUT
          echo "shared_api_id=$SHARED_API_ID" >> $GITHUB_OUTPUT
          echo "sg_id=$SG_ID" >> $GITHUB_OUTPUT
          echo "subnet1_id=$SUBNET1" >> $GITHUB_OUTPUT
          echo "subnet2_id=$SUBNET2" >> $GITHUB_OUTPUT

      # Build SAM application
      - name: SAM Build
        run: sam build --template-file infra/trainingPipelineTemplate.yaml

      # Deploy with SAM
      - name: SAM Deploy
        run: |
          sam deploy \
            --parameter-overrides \
              "SharedApiId=${{ steps.get_exports.outputs.shared_api_id }}" \
              "EEGUploadBucketName=${{ steps.get_exports.outputs.bucket_name }}" \
              "PrivateSG=${{ steps.get_exports.outputs.sg_id }}" \
              "PrivateSubnetId1=${{ steps.get_exports.outputs.subnet1_id }}" \
              "PrivateSubnetId2=${{ steps.get_exports.outputs.subnet2_id }}" \
            --no-confirm-changeset